// AUTO-GENERATED by scripts/introspect-orphan-tables.ts on 2026-05-17T13:52:29.594Z.
// DO NOT HAND-EDIT. Re-run the script when the DB schema for these tables
// changes. These 34 tables existed in the live DB but were not previously
// declared in shared/schema.ts (Bob's preferred migration path is direct
// psql ALTER per replit.md). This file gives them Drizzle type safety so
// future code can use typed queries instead of raw `db.execute(sql`...`)`.
//
// Tables: agent_evals, browser_workflows, calendar_feeds, contact_submissions, contracts, crew_agents, crew_flows, crew_tasks, customer_interactions, delegation_scratchpad, flow_steps, graph_memory, graph_memory_links, key_value_store, knowledge_nudges, knowledge_triples, kpi_metrics, marketing_calendar, marketing_results, mcp_api_keys, mind_events, mind_tickets, minds, pending_deliveries, presenter_slide_images, scheduled_posts, sculptor_sessions, security_scan_results, sessions, skill_rag_decisions, storefront_checkout_hits, tool_optimizations, tool_performance, user_profiles, webhook_events, wellbeing_interventions.

import { pgTable, bigint, boolean, date, doublePrecision, integer, jsonb, numeric, primaryKey, text, timestamp, varchar } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { customType } from "drizzle-orm/pg-core";

export const agentEvals = pgTable("agent_evals", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  personaId: integer("persona_id").notNull(),
  personaName: text("persona_name").notNull(),
  taskName: text("task_name").notNull(),
  taskPrompt: text("task_prompt").notNull(),
  judgeType: text("judge_type").notNull().default(sql`'llm'`),
  judgeCriteria: text("judge_criteria"),
  status: text("status").notNull().default(sql`'pending'`),
  passed: boolean("passed"),
  score: doublePrecision("score"),
  costUsd: doublePrecision("cost_usd"),
  durationMs: integer("duration_ms"),
  resultSummary: text("result_summary"),
  error: text("error"),
  runNumber: integer("run_number").notNull().default(1),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  completedAt: timestamp("completed_at"),
});

export const browserWorkflows = pgTable("browser_workflows", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  name: text("name").notNull(),
  url: text("url").notNull(),
  steps: jsonb("steps").notNull().default(sql`'[]'`),
  recordedActions: jsonb("recorded_actions").default(sql`'[]'`),
  createdAt: timestamp("created_at").defaultNow(),
  lastReplayed: timestamp("last_replayed"),
});

export const calendarFeeds = pgTable("calendar_feeds", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  feedName: text("feed_name").notNull(),
  feedUrl: text("feed_url").notNull(),
  feedType: text("feed_type").default(sql`'ics'`),
  lastSynced: timestamp("last_synced"),
  cachedEvents: jsonb("cached_events").default(sql`'[]'`),
  createdAt: timestamp("created_at").defaultNow(),
});

export const contactSubmissions = pgTable("contact_submissions", {
  id: integer("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull(),
  subject: text("subject").default(sql`'general'`),
  message: text("message").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const contracts = pgTable("contracts", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  customerId: integer("customer_id"),
  title: varchar("title", { length: 255 }).notNull(),
  contractType: varchar("contract_type", { length: 50 }),
  status: varchar("status", { length: 30 }).default(sql`'draft'`),
  startDate: date("start_date"),
  endDate: date("end_date"),
  value: numeric("value"),
  terms: text("terms"),
  pdfUrl: text("pdf_url"),
  driveUrl: text("drive_url"),
  signedAt: timestamp("signed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const crewAgents = pgTable("crew_agents", {
  id: integer("id").primaryKey(),
  crewId: integer("crew_id").notNull(),
  tenantId: integer("tenant_id").notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  role: varchar("role", { length: 500 }).notNull(),
  goal: text("goal").notNull(),
  backstory: text("backstory").notNull().default(sql`''`),
  personaId: integer("persona_id"),
  tools: text("tools").array().notNull().default(sql`'{}'::text[]`),
  allowDelegation: boolean("allow_delegation").notNull().default(false),
  maxIterations: integer("max_iterations").notNull().default(25),
  config: jsonb("config").notNull().default(sql`'{}'`),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const crewFlows = pgTable("crew_flows", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  description: text("description").notNull().default(sql`''`),
  state: jsonb("state").notNull().default(sql`'{}'`),
  status: varchar("status", { length: 50 }).notNull().default(sql`'idle'`),
  config: jsonb("config").notNull().default(sql`'{}'`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const crewTasks = pgTable("crew_tasks", {
  id: integer("id").primaryKey(),
  crewId: integer("crew_id").notNull(),
  tenantId: integer("tenant_id").notNull(),
  name: varchar("name", { length: 255 }),
  description: text("description").notNull(),
  expectedOutput: text("expected_output").notNull(),
  agentId: integer("agent_id"),
  contextTaskIds: integer("context_task_ids").array().notNull().default(sql`'{}'::integer[]`),
  asyncExecution: boolean("async_execution").notNull().default(false),
  outputJsonSchema: jsonb("output_json_schema"),
  tools: text("tools").array().notNull().default(sql`'{}'::text[]`),
  guardrail: text("guardrail"),
  sortOrder: integer("sort_order").notNull().default(0),
  config: jsonb("config").notNull().default(sql`'{}'`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const customerInteractions = pgTable("customer_interactions", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  customerId: integer("customer_id"),
  interactionType: varchar("interaction_type", { length: 50 }).notNull(),
  subject: varchar("subject", { length: 255 }),
  notes: text("notes"),
  outcome: varchar("outcome", { length: 100 }),
  followUpDate: date("follow_up_date"),
  createdBy: varchar("created_by", { length: 100 }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const delegationScratchpad = pgTable("delegation_scratchpad", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  chainKey: text("chain_key").notNull(),
  agentName: text("agent_name").notNull(),
  key: text("key").notNull(),
  value: text("value").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const flowSteps = pgTable("flow_steps", {
  id: integer("id").primaryKey(),
  flowId: integer("flow_id").notNull(),
  tenantId: integer("tenant_id").notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  stepType: varchar("step_type", { length: 50 }).notNull().default(sql`'start'`),
  listenTo: text("listen_to").array().notNull().default(sql`'{}'::text[]`),
  routerOutputs: text("router_outputs").array().notNull().default(sql`'{}'::text[]`),
  crewId: integer("crew_id"),
  actionType: varchar("action_type", { length: 50 }).notNull().default(sql`'crew_kickoff'`),
  actionConfig: jsonb("action_config").notNull().default(sql`'{}'`),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const graphMemory = pgTable("graph_memory", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  personaId: integer("persona_id"),
  path: text("path").notNull(),
  content: text("content").notNull(),
  triggerCondition: text("trigger_condition"),
  version: integer("version").default(1),
  parentPath: text("parent_path"),
  metadata: jsonb("metadata").default(sql`'{}'`),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
  importance: doublePrecision("importance").notNull().default(0),
  communityId: integer("community_id"),
});

export const graphMemoryLinks = pgTable("graph_memory_links", {
  id: integer("id").primaryKey(),
  sourcePath: text("source_path").notNull(),
  targetPath: text("target_path").notNull(),
  tenantId: integer("tenant_id").notNull(),
  linkType: text("link_type").default(sql`'reference'`),
  createdAt: timestamp("created_at").defaultNow(),
});

export const keyValueStore = pgTable("key_value_store", {
  key: text("key").primaryKey(),
  value: text("value").notNull().default(sql`''`),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const knowledgeNudges = pgTable("knowledge_nudges", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  fact: text("fact").notNull(),
  category: text("category").notNull().default(sql`'nudge'`),
  source: text("source").notNull().default(sql`'proactive'`),
  score: doublePrecision("score").notNull().default(0),
  conversationId: integer("conversation_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const knowledgeTriples = pgTable("knowledge_triples", {
  id: integer("id").primaryKey(),
  subject: text("subject").notNull(),
  predicate: text("predicate").notNull(),
  object: text("object").notNull(),
  confidence: doublePrecision("confidence").notNull().default(1.0),
  source: text("source").notNull().default(sql`'agent'`),
  validFrom: timestamp("valid_from").defaultNow(),
  validUntil: timestamp("valid_until"),
  wing: text("wing"),
  room: text("room"),
  tenantId: integer("tenant_id").notNull(),
  personaId: integer("persona_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  meta: jsonb("meta").default(sql`'{}'`),
});

export const kpiMetrics = pgTable("kpi_metrics", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  metricName: varchar("metric_name", { length: 100 }).notNull(),
  category: varchar("category", { length: 50 }).notNull(),
  value: numeric("value").notNull(),
  target: numeric("target"),
  unit: varchar("unit", { length: 30 }).default(sql`'count'`),
  period: varchar("period", { length: 20 }).default(sql`'monthly'`),
  periodStart: date("period_start").notNull().default(sql`CURRENT_DATE`),
  notes: text("notes"),
  recordedAt: timestamp("recorded_at", { withTimezone: true }).defaultNow(),
});

export const marketingCalendar = pgTable("marketing_calendar", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  platform: text("platform").notNull().default(sql`'x'`),
  content: text("content").notNull(),
  scheduledDate: timestamp("scheduled_date").notNull(),
  style: text("style"),
  campaign: text("campaign"),
  status: text("status").notNull().default(sql`'scheduled'`),
  createdAt: timestamp("created_at").defaultNow(),
});

export const marketingResults = pgTable("marketing_results", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  platform: text("platform").notNull().default(sql`'x'`),
  content: text("content"),
  campaign: text("campaign"),
  views: integer("views").default(0),
  likes: integer("likes").default(0),
  replies: integer("replies").default(0),
  reposts: integer("reposts").default(0),
  clicks: integer("clicks").default(0),
  bookmarks: integer("bookmarks").default(0),
  score: numeric("score").default("0"),
  postedAt: timestamp("posted_at").defaultNow(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const mcpApiKeys = pgTable("mcp_api_keys", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  name: text("name").notNull(),
  keyPrefix: text("key_prefix").notNull(),
  keyHash: text("key_hash").notNull(),
  scopes: text("scopes").array().notNull().default(sql`'{}'::text[]`),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
  revokedAt: timestamp("revoked_at", { withTimezone: true }),
  createdBy: text("created_by"),
});

export const mindEvents = pgTable("mind_events", {
  id: integer("id").primaryKey(),
  mindId: integer("mind_id").notNull(),
  tenantId: integer("tenant_id").notNull(),
  eventType: varchar("event_type", { length: 100 }).notNull(),
  source: varchar("source", { length: 200 }).notNull().default(sql`'user'`),
  payload: jsonb("payload").notNull().default(sql`'{}'`),
  handled: boolean("handled").notNull().default(false),
  handledAt: timestamp("handled_at"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const mindTickets = pgTable("mind_tickets", {
  id: integer("id").primaryKey(),
  mindId: integer("mind_id").notNull(),
  tenantId: integer("tenant_id").notNull(),
  title: varchar("title", { length: 500 }).notNull(),
  description: text("description").notNull().default(sql`''`),
  acceptanceCriteria: text("acceptance_criteria").notNull().default(sql`''`),
  priority: integer("priority").notNull().default(2),
  ticketType: varchar("ticket_type", { length: 50 }).notNull().default(sql`'task'`),
  status: varchar("status", { length: 30 }).notNull().default(sql`'ready'`),
  assignedAgentId: varchar("assigned_agent_id", { length: 200 }),
  dependsOn: integer("depends_on").array(),
  result: jsonb("result"),
  verdict: jsonb("verdict"),
  nextSteps: text("next_steps"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const minds = pgTable("minds", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  name: varchar("name", { length: 200 }).notNull(),
  purpose: text("purpose").notNull().default(sql`''`),
  soul: text("soul").notNull().default(sql`''`),
  status: varchar("status", { length: 30 }).notNull().default(sql`'active'`),
  config: jsonb("config").notNull().default(sql`'{}'`),
  talkingPersonaId: integer("talking_persona_id"),
  thinkingPersonaId: integer("thinking_persona_id"),
  maxConcurrentWorkers: integer("max_concurrent_workers").notNull().default(5),
  memory: jsonb("memory").notNull().default(sql`'{}'`),
  workLog: jsonb("work_log").notNull().default(sql`'[]'`),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const pendingDeliveries = pgTable("pending_deliveries", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  conversationId: integer("conversation_id").notNull(),
  deliveryType: text("delivery_type").notNull().default(sql`'presentation'`),
  payload: jsonb("payload").notNull(),
  delivered: boolean("delivered").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const presenterSlideImages = pgTable("presenter_slide_images", {
  id: integer("id").primaryKey(),
  sessionId: integer("session_id").notNull(),
  slideIndex: integer("slide_index").notNull(),
  imageData: customType<{ data: Buffer }>({ dataType: () => "bytea" })("image_data").notNull(),
  imageSize: integer("image_size").notNull().default(0),
  quality: text("quality").notNull().default(sql`'full'`),
  createdAt: timestamp("created_at").defaultNow(),
});

export const scheduledPosts = pgTable("scheduled_posts", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  platforms: text("platforms").array().notNull(),
  content: text("content").notNull(),
  imageUrl: text("image_url"),
  imageBase64: text("image_base64"),
  scheduledFor: timestamp("scheduled_for", { withTimezone: true }).notNull(),
  status: text("status").notNull().default(sql`'pending'`),
  attempts: integer("attempts").notNull().default(0),
  maxAttempts: integer("max_attempts").notNull().default(3),
  lastError: text("last_error"),
  perPlatformResults: jsonb("per_platform_results").notNull().default(sql`'{}'`),
  campaign: text("campaign"),
  createdBy: text("created_by"),
  lockedAt: timestamp("locked_at", { withTimezone: true }),
  lockedBy: text("locked_by"),
  nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  videoUrl: text("video_url"),
});

export const sculptorSessions = pgTable("sculptor_sessions", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  title: text("title").notNull(),
  task: text("task").notNull(),
  plan: jsonb("plan").default(sql`'[]'`),
  personaId: integer("persona_id"),
  model: text("model"),
  status: text("status").default(sql`'pending'`),
  conversationId: integer("conversation_id"),
  parentSessionId: integer("parent_session_id"),
  comparisonGroup: text("comparison_group"),
  result: text("result"),
  reviewResult: jsonb("review_result"),
  toolCallsCount: integer("tool_calls_count").default(0),
  tokensUsed: integer("tokens_used").default(0),
  startedAt: timestamp("started_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  metadata: jsonb("metadata").default(sql`'{}'`),
});

export const securityScanResults = pgTable("security_scan_results", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  scanType: text("scan_type").notNull(),
  grade: text("grade"),
  score: integer("score"),
  findings: jsonb("findings").default(sql`'[]'`),
  summary: text("summary"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const sessions = pgTable("sessions", {
  sid: varchar("sid").primaryKey(),
  sess: jsonb("sess").notNull(),
  expire: timestamp("expire").notNull(),
});

export const skillRagDecisions = pgTable("skill_rag_decisions", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  question: text("question").notNull(),
  invoked: boolean("invoked").notNull().default(false),
  gateReason: text("gate_reason"),
  judgeConfidence: numeric("judge_confidence"),
  judgeReason: text("judge_reason"),
  skillUsed: text("skill_used").notNull().default(sql`'none'`),
  rewrittenQuery: text("rewritten_query"),
  subQuestions: text("sub_questions"),
  exited: boolean("exited").notNull().default(false),
  candidatesIn: integer("candidates_in").notNull().default(0),
  candidatesOut: integer("candidates_out").notNull().default(0),
  totalMs: integer("total_ms").notNull().default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const storefrontCheckoutHits = pgTable("storefront_checkout_hits", {
  id: bigint("id", { mode: "number" }).primaryKey(),
  rateKey: text("rate_key").notNull(),
  hitAt: timestamp("hit_at", { withTimezone: true }).notNull().defaultNow(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
});

export const toolOptimizations = pgTable("tool_optimizations", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  toolName: text("tool_name").notNull(),
  optimizationType: text("optimization_type").notNull().default(sql`'description'`),
  originalHint: text("original_hint"),
  optimizedHint: text("optimized_hint").notNull(),
  failurePattern: text("failure_pattern"),
  improvementScore: doublePrecision("improvement_score"),
  applied: boolean("applied").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const toolPerformance = pgTable("tool_performance", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  toolName: text("tool_name").notNull(),
  successCount: integer("success_count").notNull().default(0),
  failCount: integer("fail_count").notNull().default(0),
  totalDurationMs: bigint("total_duration_ms", { mode: "number" }).notNull().default(0),
  lastFailureReason: text("last_failure_reason"),
  lastSuccessAt: timestamp("last_success_at", { withTimezone: true }),
  lastFailureAt: timestamp("last_failure_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const userProfiles = pgTable("user_profiles", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  observations: jsonb("observations").notNull().default(sql`'[]'`),
  communicationStyle: text("communication_style"),
  decisionPatterns: text("decision_patterns"),
  preferences: jsonb("preferences").notNull().default(sql`'{}'`),
  personalityTraits: jsonb("personality_traits").notNull().default(sql`'{}'`),
  interactionCount: integer("interaction_count").notNull().default(0),
  lastDerivedAt: timestamp("last_derived_at", { withTimezone: true }),
  lastConsolidatedAt: timestamp("last_consolidated_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const webhookEvents = pgTable("webhook_events", {
  provider: text("provider").notNull(),
  eventId: text("event_id").notNull(),
  receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow(),
  completedAt: timestamp("completed_at", { withTimezone: true }),
}, (t) => ({ pk: primaryKey({ columns: [t.provider, t.eventId] }) }));

export const wellbeingInterventions = pgTable("wellbeing_interventions", {
  id: integer("id").primaryKey(),
  tenantId: integer("tenant_id").notNull(),
  userId: text("user_id"),
  interventionId: text("intervention_id").notNull(),
  interventionType: text("intervention_type").notNull().default(sql`'micro_sabbatical'`),
  fatigueType: text("fatigue_type"),
  shameIntensity: text("shame_intensity"),
  triggerKeywords: text("trigger_keywords"),
  accepted: boolean("accepted"),
  feedback: text("feedback"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});
