#!/usr/bin/env tsx
/**
 * scripts/refresh-totals.ts — regenerates docs/CURRENT_PLATFORM_TOTALS.md
 * from live registries.
 *
 * Sources:
 *   tools     → rg "registerTool(...)" -or '$1' server/ | sort -u | wc -l
 *   tables-D  → rg -c "= pgTable(" shared/schema.ts (declared)
 *   tables-L  → SELECT count(*) FROM information_schema.tables WHERE table_schema='public'
 *   skills    → SELECT count(*) FROM skills
 *   personas  → SELECT count(*) FROM personas WHERE is_active=true
 *   gov rules → SELECT count(*) FROM governance_rules
 *   indexes   → SELECT count(*) FROM pg_indexes WHERE schemaname='public' AND indexname NOT LIKE '%_pkey'
 *
 * Usage:
 *   npx tsx scripts/refresh-totals.ts          # rewrite docs/CURRENT_PLATFORM_TOTALS.md
 *   npx tsx scripts/refresh-totals.ts --check  # exit 1 if doc would change (CI gate)
 *   npx tsx scripts/refresh-totals.ts --json   # emit numbers as JSON, no file write
 *
 * Env: DATABASE_URL required.
 *
 * Idempotent: re-runs produce the same output for the same inputs.
 * Safe: read-only against DB and source tree; only mutates the totals doc.
 */
import { execSync } from "node:child_process";
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { Pool } from "pg";

const TOTALS_PATH = "docs/CURRENT_PLATFORM_TOTALS.md";
const CHECK = process.argv.includes("--check");
const JSON_ONLY = process.argv.includes("--json");

function sh(cmd: string): string {
  return execSync(cmd, { encoding: "utf8" }).trim();
}

async function main() {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) {
    console.error("[refresh-totals] DATABASE_URL not set — cannot query live counts");
    process.exit(2);
  }

  const tools = parseInt(
    sh(`rg "registerTool\\(['\\"]([a-z_0-9]+)['\\"]" -or '$1' server/ | sort -u | wc -l`),
    10,
  );
  const tablesDeclared = parseInt(sh(`rg -c "= pgTable\\(" shared/schema.ts`), 10);

  const pool = new Pool({ connectionString: databaseUrl });
  try {
    const [tablesLive, skills, personas, gov, indexes] = await Promise.all([
      pool.query("SELECT count(*)::int AS n FROM information_schema.tables WHERE table_schema='public'"),
      pool.query("SELECT count(*)::int AS n FROM skills"),
      pool.query("SELECT count(*)::int AS n FROM personas WHERE is_active=true"),
      pool.query("SELECT count(*)::int AS n FROM governance_rules"),
      pool.query("SELECT count(*)::int AS n FROM pg_indexes WHERE schemaname='public' AND indexname NOT LIKE '%_pkey'"),
    ]);

    const counts = {
      tools,
      tablesDeclared,
      tablesLive: tablesLive.rows[0].n,
      skills: skills.rows[0].n,
      personas: personas.rows[0].n,
      governance: gov.rows[0].n,
      indexes: indexes.rows[0].n,
      verifiedAt: new Date().toISOString().slice(0, 10),
    };

    if (JSON_ONLY) {
      console.log(JSON.stringify(counts, null, 2));
      return;
    }

    const skillsTotal = counts.skills + 4; // 4 platform agent skills in .agents/skills/

    const next = `# Current Platform Totals — Single Source of Truth

> **This is the authoritative count for VisionClaw Agent.** Every other doc
> (README, SETUP, FORK-SETUP, ROADMAP, CONTRIBUTING, GitHub repo description)
> must agree with the numbers here. If you find a mismatch, fix the other doc
> — not this one.
>
> **Auto-refresh:** run \`npx tsx scripts/refresh-totals.ts\` to regenerate
> this file from live registries.

**Last verified:** ${counts.verifiedAt} (auto-generated by \`scripts/refresh-totals.ts\`)
**Verification method:** Live runtime counts from the production database
plus source-tree grep against \`server/\` and \`shared/schema.ts\`.

---

## Authoritative Counts

| Metric | Value | How it's verified |
|---|---|---|
| **AI agent personas (active)** | **${counts.personas}** | \`SELECT count(*) FROM personas WHERE is_active=true\` |
| **Built-in tools** | **${counts.tools}** | \`rg "registerTool(...)" server/ \\| sort -u \\| wc -l\` |
| **Skills (DB seeded)** | **${counts.skills}** | \`SELECT count(*) FROM skills\` |
| **Skills (total incl. .agents/skills/)** | **${skillsTotal}** | DB count + 4 platform agent skills not yet seeded |
| **Database tables (declared)** | **${counts.tablesDeclared}** | \`rg -c "= pgTable(" shared/schema.ts\` |
| **Database tables (live in \`public\` schema)** | **${counts.tablesLive}** | \`SELECT count(*) FROM information_schema.tables WHERE table_schema='public'\` |
| **Governance rules** | **${counts.governance}** | \`SELECT count(*) FROM governance_rules\` |
| **Production indexes (non-PK)** | **${counts.indexes}** | \`SELECT count(*) FROM pg_indexes WHERE schemaname='public' AND indexname NOT LIKE '%_pkey'\` |
| **AI providers** | **6** | OpenAI, Anthropic, Google, xAI, OpenRouter, Perplexity |
| **AI models (core registry)** | **36 curated** | \`MODEL_REGISTRY.length\` in \`server/providers.ts\` |
| **AI models (daily catalog discovery)** | **1000+** | Nightly OpenRouter scanner (\`server/model-catalog.ts\`) |

---

## Why the schema-declared vs. live-DB delta exists

The HyperAgent review of 2026-05-06 flagged the historical confusion between
\`shared/schema.ts\` declarations and live database table count. To remove
ambiguity:

- **${counts.tablesDeclared} declared** — auditable, version-controlled,
  type-safe Drizzle schema in \`shared/schema.ts\`. This is what \`db:push\`
  manages and what \`tests/security/\` locks down.
- **${counts.tablesLive} live** — includes the four externally-managed Stripe
  Sync mirror tables (\`stripe.accounts/products/prices/payment_intents\`),
  internal pgvector tables, and historical tables not yet pruned.

Use the declared number for code reviews and schema audits. Use the live
number for ops/observability. Headline marketing copy may round to a single
combined figure as long as it stays within these bounds.

---

## How to keep this current

1. After any release that adds tools/skills/tables/personas, run
   \`npx tsx scripts/refresh-totals.ts\`.
2. The \`Auto Git Push\` workflow runs the refresh on every quiet-window
   commit, so the file stays self-consistent within ~90s of any change.
3. The public mirror pulls this file through unchanged. Reference it in
   \`README-PUBLIC.md\` (link, not hardcoded numbers).

_Re-run with \`--check\` in CI to gate that the doc is up to date._
`;

    if (CHECK) {
      const cur = existsSync(TOTALS_PATH) ? readFileSync(TOTALS_PATH, "utf8") : "";
      if (cur !== next) {
        console.error(`[refresh-totals] ${TOTALS_PATH} is STALE — run without --check to regenerate`);
        process.exit(1);
      }
      console.log(`[refresh-totals] ${TOTALS_PATH} is current`);
      return;
    }

    writeFileSync(TOTALS_PATH, next);
    console.log(`[refresh-totals] OK — ${TOTALS_PATH} regenerated`);
    console.log(`  tools=${counts.tools} skills=${counts.skills}(+4=${skillsTotal}) personas=${counts.personas} tables=${counts.tablesDeclared}(declared)/${counts.tablesLive}(live) gov=${counts.governance} idx=${counts.indexes}`);
  } finally {
    await pool.end();
  }
}

main().catch(err => {
  console.error("[refresh-totals] FAILED:", err?.message || err);
  process.exit(3);
});
