import { uploadAndShare } from "../server/google-drive";
import { getOrCreateTenantInbox, sendEmail } from "../server/email";
import { db } from "../server/db";
import { sql } from "drizzle-orm";
import { readFileSync, writeFileSync } from "fs";

(async () => {
  try {
    const PDF_RESULT = JSON.parse(readFileSync("/tmp/pdf-result.json", "utf8"));
    const PDF_URL = PDF_RESULT.viewUrl;
    const PDF_DOWNLOAD = PDF_RESULT.downloadUrl;
    process.stdout.write("PDF_URL_LOADED:" + PDF_URL + "\n");

    process.stdout.write("STEP_1_UPLOAD_TXT\n");
    const txtResult = await uploadAndShare({
      filePath: "VisionClaw-Comprehensive-Features.txt",
      fileName: "VisionClaw-Comprehensive-Features.txt",
      description: "VisionClaw Agent Platform — Complete Feature Document (Text)",
      folderLabel: "Platform Documentation",
      share: true,
    });
    process.stdout.write("TXT_RESULT:" + JSON.stringify(txtResult) + "\n");
    writeFileSync("/tmp/txt-result.json", JSON.stringify(txtResult, null, 2));
    const TXT_URL = (txtResult as any).viewUrl || (txtResult as any).webViewLink;
    const TXT_DOWNLOAD = (txtResult as any).downloadUrl;

    process.stdout.write("STEP_2_FETCH_STATS\n");
    const statsRes = await db.execute(sql`
      SELECT
        (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public') AS tables,
        (SELECT COUNT(*) FROM skills) AS skills,
        (SELECT COUNT(*) FROM personas WHERE is_active = true) AS personas,
        (SELECT COUNT(*) FROM research_programs WHERE is_active = true) AS programs,
        (SELECT COUNT(*) FROM research_experiments) AS experiments,
        (SELECT COUNT(*) FROM code_proposals) AS proposals_total,
        (SELECT COUNT(*) FROM code_proposals WHERE status = 'ready') AS proposals_ready
    `);
    const s: any = ((statsRes as any).rows || (statsRes as any))[0];

    process.stdout.write("STEP_3_EMAIL\n");
    const inboxRes = await getOrCreateTenantInbox(1);
    const inboxId =
      typeof inboxRes === "string" ? inboxRes : (inboxRes as any).inboxId || (inboxRes as any).email;

    const SNAPSHOT_DATE = new Date().toISOString().slice(0, 10);
    const emailText =
      `VisionClaw Comprehensive Features — refreshed ${SNAPSHOT_DATE}\n\n` +
      `Two updated documents are now available in your Google Drive (Platform Documentation folder):\n\n` +
      `PDF (premium styled, dark gradient cover, 272 tools + ${s.skills} skills + ${s.personas} personas + every subsystem):\n` +
      `  View:     ${PDF_URL}\n` +
      `  Download: ${PDF_DOWNLOAD}\n\n` +
      `Text (plain text, identical exhaustive content — Felix uses this as his knowledge base for presentations):\n` +
      `  View:     ${TXT_URL}\n` +
      `  Download: ${TXT_DOWNLOAD || "(use View link)"}\n\n` +
      `Snapshot stats:\n` +
      `  - Tools:                     272\n` +
      `  - Skills:                    ${s.skills}\n` +
      `  - Personas (active):         ${s.personas}\n` +
      `  - DB tables:                 ${s.tables}\n` +
      `  - Project source files:      ~505\n` +
      `  - TS/TSX LOC:                192,489\n` +
      `  - Research programs:         ${s.programs} active, ${s.experiments} experiments run\n` +
      `  - Code proposals:            ${s.proposals_ready} READY of ${s.proposals_total} total\n\n` +
      `Generated by the post-edit pipeline.\n\n` +
      `— VisionClaw Agent\n`;

    const emailRes = await sendEmail({
      inboxId,
      to: process.env.OWNER_ALERT_EMAIL || "huskyauto@gmail.com",
      subject: "VisionClaw Updated Features — PDF + Text",
      text: emailText,
    });
    process.stdout.write("EMAIL_RESULT:" + JSON.stringify(emailRes) + "\n");

    process.stdout.write("\n=== PIPELINE COMPLETE ===\n");
    process.stdout.write(`PDF_URL: ${PDF_URL}\n`);
    process.stdout.write(`TXT_URL: ${TXT_URL}\n`);
    process.exit(0);
  } catch (e: any) {
    process.stderr.write("ERROR:" + (e?.message || String(e)) + "\n");
    process.stderr.write((e?.stack || "") + "\n");
    process.exit(1);
  }
})();
